version: '3.8'

services:

  ecommerce-spring:
    image: mysql:latest
    container_name: ecommerce-app
    environment:
      MYSQL_ROOT_PASSWORD: delight123
      MYSQL_DATABASE: ecommerce-spring-cloud

    ports:
      - "3309:3306"
    volumes:
      - mysql-ecommerce-data:/mysqldata

  redis-cart-spring:
    image: redis:latest
    container_name: cart-spring
    ports:
      - 6380:6379
    command: ["redis-server","--appendonly", "yes"]

    volumes:
      - redis-cart-data:/data


volumes:
  redis-cart-data:
  mysql-ecommerce-data: